Error: sidebarMenuButtonVariants is not defined
In HTML, whitespace text nodes cannot be a child of <html>. Make sure you don't have any extra whitespace between tags on each line of your source code.
This will cause a hydration error.